### ISSUE TITLE
API displays events and planning publicly

### ISSUE THREAD

**Issue by bmg1919** [superdesk/superdesk-planning#1504]
/api/events and /api/planning both display xml publicly without authentication.

All other resources present error 401 when accessed without authentication, as it should be.

**Comment by FourthEstateOrg** [comment]
We can confirm this behavior.

Content is exposed.

**Comment by MarkLark86** [comment]
All API endpoints now require authentication. The following is a list of the new versions (and their respective git branch)

In development versions:
- **v2.2.dev** - develop
- **v2.1.0.rc3** - release/2.1

Stable versions (released to npmjs/pypi):
- **v2.0.2** - master
- **v1.34.0** - support/1.34
- **v1.33.3** - support/1.33
- **v1.32.0** - support/1.32
