### ISSUE TITLE
Adding the plugin

### ISSUE THREAD

**Issue by CrazyEyesPete** [superdesk/superdesk-planning#569]
Regardless of what commit version I try I get an error. I've tried a few other ideas to get Planner to install but no luck. Please see screenshot.
![screen shot 2017-12-04 at 3 19 17 pm](https://user-images.githubusercontent.com/18177830/33574348-bd041d76-d906-11e7-8488-b58693e8f0fb.png)

**Comment by pablopunk** [comment]
@CrazyEyesPete that seems like the JSON is missing a trailing comma in the previous line, try to fix that or paste the content of your package.json here

**Comment by pablofigueroa32** [comment]
I have the same problem 
This is the package.json
{
    "name": "superdesk",
    "license": "GPL-3.0",
    "dependencies": {
        "superdesk-core": "1.13.0",
        "superdesk-publisher": "superdesk/superdesk-publisher#dc87654"
        "superdesk-planning": "superdesk/superdesk-planning#master"
    }
}

any help?

**Comment by e1th0r** [comment]
Pablo, you need fix the syntax for package.json file. Rigth format is

{
"name": "superdesk",
"license": "GPL-3.0",
"dependencies": {
                   "superdesk-core": "1.13.0",
                   "superdesk-publisher": "superdesk/superdesk-publisher#dc87654",
                   "superdesk-planning": "superdesk/superdesk-planning#master"
                          }
}

Nothe the comma at the ned of publisher plugin line.

Please comment if this tip solve your issue.

**Comment by trondhuso** [comment]
I believe this issue can be closed. No comment since 2018 and as @pablofigueroa32 writes - the syntax is wrong with missing commas at the end of the lines under dependencies.
